/*
 * More algorithms for each OLL and PLL case (besides the main one in algs.ts),
 * for the algorithm pages. From the SpeedSolving wiki's OLL and PLL pages, and
 * each one checked: it was kept only if it really solves its case on our cube
 * model (cases.test.ts checks them again).
 */

export const ALTERNATIVE_ALGS: Record<string, string[]> = {
  "OLL 1": ["R U' R2 D' r U' r' D R2 U R'"],
  "OLL 2": ["R U' R2 D' r U r' D R2 U R'", "f U R U' R' S' U R U' R' F'"],
  "OLL 3": ["r' R2 U R' U r U2 r' U M'", "L' l U l' U2 l U L' U L M'", "R' F2 R2 U2 R' F R U2 R2 F2 R"],
  "OLL 4": ["l L2 U' L U' l' U2 l U' M'", "R r' U' r U2 r' U' R U' R2 r", "R' F2 R2 U2 R' F' R U2 R2 F2 R"],
  "OLL 5": ["l' U2 L U L' U l"],
  "OLL 6": [],
  "OLL 7": [],
  "OLL 8": ["l' U' L U' L' U2 l", "R U2 R' U2 R' F R F'"],
  "OLL 9": [],
  "OLL 10": ["F U F' R' F R U' R' F' R"],
  "OLL 11": ["r' R2 U R' U R U2 R' U M'"],
  "OLL 12": ["l L2 U' L U' L' U2 L U' M'"],
  "OLL 13": ["F U R U' R2 F' R U R U' R'", "r U' r' U' r U r' F' U F"],
  "OLL 14": [],
  "OLL 15": ["l' U' l L' U' L U l' U l"],
  "OLL 16": [],
  "OLL 17": ["F R' F' R U S' R U' R' S"],
  "OLL 18": ["R U R2 F' U' F U R U2 R' F R F'", "F R U R' d R' U2 R' F R F'", "r U R' U R U2 r2 U' R U' R' U2 r"],
  "OLL 19": ["S' R U R' S U' R' F R F'"],
  "OLL 20": ["r U R' U' r R' M' U R U' R' U' M'", "S' R U R' S U' M' U R U' r'", "M U R U R' U' M2 U R U' r'"],
  "OLL 21": ["R U2 R' U' R U R' U' R U' R'"],
  "OLL 22": ["f R U R' U' S' R U R' U' F'"],
  "OLL 23": ["R2 D R' U2 R D' R' U2 R'"],
  "OLL 24": ["l' U' L U l F' L' F"],
  "OLL 25": ["F' r U R' U' r' F R", "F R B R' F' R B' R'", "F l U l' F' l U' l'"],
  "OLL 26": ["R' U' R U' R' U2 R", "L' U' L U' L' U2 L"],
  "OLL 27": ["R' U2 R U R' U R"],
  "OLL 28": ["U2 M' U l L' U2 M' U l L'", "U2 M' U M U2 M' U M"],
  "OLL 29": ["R U R' U' R' F R F' R U R' U' M' U R U' r'", "r2 D' r U r' D r2 U' r' U' r"],
  "OLL 30": ["r' D' r U' r' D r2 U' r' U r U r'", "F R' F R2 U' R' U' R U R' F2"],
  "OLL 31": [],
  "OLL 32": ["S R U R' U' R' F R f'", "L U F' U' L' U L F L'"],
  "OLL 33": [],
  "OLL 34": ["R U R' U' y l' U' L U L' l", "f R f' U' r' U' R U M'"],
  "OLL 35": [],
  "OLL 36": ["R U R' F' R U R' U' R' F R U' R' F R F'", "R' F' U' F2 U R U' R' F' R", "R U R2 F' U' F U R2 U2 R'"],
  "OLL 37": [],
  "OLL 38": [],
  "OLL 39": ["L F' L' U' L U F U' L'", "f' r U r' U' r' F r S"],
  "OLL 40": [],
  "OLL 41": [],
  "OLL 42": ["R' U' R U' R' U2 R U R' F' U' F U R", "R' F R F' R' F R F' R U R' U' R U R'", "F R' F' R U2 R' U' R2 U' R2 U2 R"],
  "OLL 43": [],
  "OLL 44": ["F U R U' R' F'"],
  "OLL 45": [],
  "OLL 46": [],
  "OLL 47": ["R' U' R' F R F' R' F R F' U R", "F' L' U' L U L' U' L U F", "R' F' U' F U F' U' F U R"],
  "OLL 48": [],
  "OLL 49": ["R B' R2 F R2 B R2 F' R"],
  "OLL 50": ["R' F R2 B' R2 F' R2 B R'"],
  "OLL 51": ["F U R U' R' U R U' R' F'"],
  "OLL 52": ["R U R' U R U' B U' B' R'"],
  "OLL 53": ["l' U' L U' L' U L U' L' U2 l", "r' U2 R U R' U' R U R' U r"],
  "OLL 54": ["r U2 R' U' R U R' U' R U' r'"],
  "OLL 55": ["R' F U R U' R2 F' R2 U R' U' R", "r U2 R' U' r' R2 U R' U' r U' r'"],
  "OLL 56": ["r U r' U R U' R' M' U R U2 r'"],
  "OLL 57": [],
  "PLL Aa": ["R' F R' B2 R F' R' B2 R2", "l' U R' D2 R U' R' D2 R2"],
  "PLL Ab": ["R B' R F2 R' B R F2 R2", "l' R' D2 R U R' D2 R U' R x'"],
  "PLL E": ["R2 U R' U' y R U R' U' R U R' U' R U R' y' R U' R2", "x' L' U L D' L' U' L D L' U' L D' L' U L D x"],
  "PLL F": ["y L R2 U R U R2 U' R' U' R2 U' R U2 L' U R'", "y x R' B' U' l U R' U' R' F R2 U' R' U' R U R' U R", "y2 R' U2 R' d' R' F' R2 U' R' U R' F R U' F"],
  "PLL Ga": ["R2 U R' U R' U' R U' R2 D U' R' U R D'", "R2 u R' U R' U' R u' R2 y' R' U R", "F2 D R' U R' U' R D' F2 L' U L"],
  "PLL Gb": ["R' U' R y R2 u R' U R U' R u' R2", "F' U' F R2 u R' U R U' R u' R2", "R' U2 R U' F R U R' U' R' F' U' R U R U' R' y2"],
  "PLL Gc": ["R2 U' R U' R U R' U R2 D' U R U' R' D", "R2 F2 R U2 R U2 R' F R U R' U' R' F R2", "R2 u' R U' R U R' u R2 y R U' R'"],
  "PLL Gd": ["D' R U R' U' D R2 U' R U' R' U R' U R2", "R U R' y' R2 u' R U' R' U R' u R2", "R U R' F2 D' L U' L' U L' D F2"],
  "PLL H": ["M2 U' M2 U2 M2 U' M2"],
  "PLL Ja": ["L U' R' U L' U2 R U' R' U2 R", "U R U R' U' R' F R2 U' R' U2 R U R' F' R U R' U' R' F R F'", "U R' U' R B R' U' R U l U' R2 F R x"],
  "PLL Jb": ["R' U L U' R U2 L' U L U2 L'", "R U R' F' R U R' U' R' F R2 U' R' U'", "R U2 R' U' R U2 L' U R' U' r x"],
  "PLL Na": ["F' R U R' U' R' F R2 F U' R' U' R U F' R'", "R F U' R' U R U F' R2 F' R U R U' R' F", "z U' F R F' R' F' U F2 U R' F' R' F R U' F' z'"],
  "PLL Nb": ["R' U r' F2 R F' M' U r' F2 R F' r U", "R' U R U' R' F' U' F R U R' U' R U' f R f'", "B R' U' R U R B' R2 B' U R U R' U' B R"],
  "PLL Ra": ["R U R' F' R U2 R' U2 R' F R U R U2 R' U'", "R U2 R' U2 R B' R' U' R U R B R2 U", "R U2 R' U2 R B' R' U' R U l U R2 x"],
  "PLL Rb": ["R' U2 R U2 R' F R U R' U' R' F' R2 U'", "L' U' L F L' U2 L U2 L F' L' U' L' U2 L U", "R' U2 R U2 R' F R U R' U' l' U' R2 x'"],
  "PLL T": ["F R U' R' U R U R2 F' R U R U' R'", "R U R' U' R' F R2 U' R' U F' L' U L", "R2 U R2 U' R2 U' D R2 U' R2 U R2 D'"],
  "PLL Ua": ["M2 U M U2 M' U M2", "R2 U' R' U' R U R U R U' R"],
  "PLL Ub": ["M2 U' M U2 M' U' M2", "R' U R' U' R' U' R' U R U R2"],
  "PLL V": ["R' U R' U' R D' R' D R' U D' R2 U' R2 D R2", "R' U R U' R' f' U' R U2 R' U' R U' R' f R", "R' f' R U R' U R U2 R' U f R U R' U' R"],
  "PLL Y": ["R' U' R U' L R U2 R' U' R U2 L' U R2 U R", "R2 U' R' U R U' x D' R' U R' U' R' D R", "F R' F R2 U' R' U' R U R' F' R U R' U' F'"],
  "PLL Z": ["M2 U M2 U M' U2 M2 U2 M'", "M2 U' M2 U' M U2 M2 U2 M"],
};
